version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurant
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  order-service:
    build:
      context: ./order-service
    depends_on:
      - mysql
      - rabbitmq
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: restaurant
      RABBITMQ_URL: amqp://rabbitmq
    ports:
      - "3000:3000"

  kitchen-service:
    build:
      context: ./kitchen-service
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://rabbitmq

  notification-service:
    build:
      context: ./notification-service
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://rabbitmq

volumes:
  mysql_data:
